version: '3.4'
services:
    kafka:
       image: "ulekha/kafka:latest"
       container_name: kafka
       hostname: kafka
       ports:
          - "9092:9092"
          - "9093:9093"
          - "9094:9094"
       volumes:
          - ~/zookeeper:/tmp/zookeeper
          - ~/kafka-logs:/tmp/kafka-logs
          - ~/kafka1-logs:/tmp/kafka1-logs
          - ~/kafka2-logs:/tmp/kafka2-logs
