version: '3.4'
services:
    kafka:
       image: "ulekha/kafka:latest"
       container_name: kafka
       hostname: kafka
       ports:
          - "2181:2181"
          - "9092:9092"
          - "29092:29092"